In [1]:
import importlib

import pandas as pd
import numpy as np

import attrition_analysis.data_selection as data_selection
import attrition_analysis.models_utils as models_utils

importlib.reload(data_selection)
importlib.reload(models_utils)

from attrition_analysis.models_utils import (
    split_train_test_df,
    estimators_dict,
    param_distributions_dict,
    categorical_models_dict_c,
    mixed_models_dict_c,
    run_logistic_cross_validation,
    run_logistic_gap_analysis,
    run_logistic_model_comparison,
    tune_logistic_hyperparameters_top_combinations,
    evaluate_thresholds_optimized_logistic_models_cv
)


df = pd.read_csv("../../data/clean/Employee-Attrition_Clean.csv")

target = "AttritionFlag"

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,EducationField,EmployeeCount,EmployeeNumber,Gender,...,IncomeGroup,EducationLevel,StockOption,JobLevelGroup,SatisfactionLevel,PerformanceRatingLevel,EnvironmentSatisfactionLevel,JobInvolvementLevel,RelationshipSatisfactionLevel,WorkLifeBalanceLevel
0,41,Yes,Travel_Rarely,1102,Sales,1,Life Sciences,1,1,Female,...,Medium,College,No Options,Junior Level,Very High,Excellent,Medium,High,Low,Bad
1,49,No,Travel_Frequently,279,Research & Development,8,Life Sciences,1,2,Male,...,Medium,Below College,Low,Junior Level,Medium,Outstanding,High,Medium,Very High,Better
2,37,Yes,Travel_Rarely,1373,Research & Development,2,Other,1,4,Male,...,Low,College,No Options,Entry Level,High,Excellent,Very High,Medium,Medium,Better
3,33,No,Travel_Frequently,1392,Research & Development,3,Life Sciences,1,5,Female,...,Low,Master,No Options,Entry Level,High,Excellent,Very High,High,High,Better
4,27,No,Travel_Rarely,591,Research & Development,2,Medical,1,7,Male,...,Medium,Below College,Low,Entry Level,Medium,Excellent,Low,High,Very High,Better

In [17]:
all_logistic_models_dict_c = {
    **categorical_models_dict_c,
    **mixed_models_dict_c
}

len(all_logistic_models_dict_c)

15

In [18]:
df_train, df_test = split_train_test_df(
    df=df,
    target=target,
    test_size=0.30,
    random_state=42
)

print("Train shape:", df_train.shape)
print("Test shape:", df_test.shape)

print("\nTrain target distribution:")
display(df_train[target].value_counts(normalize=True).round(3))

print("\nTest target distribution:")
display(df_test[target].value_counts(normalize=True).round(3))

Train shape: (1029, 43)
Test shape: (441, 43)

Train target distribution:

AttritionFlag
0    0.839
1    0.161
Name: proportion, dtype: float64

Test target distribution:

AttritionFlag
0    0.839
1    0.161
Name: proportion, dtype: float64

In [19]:
cv_comparison = run_logistic_cross_validation(
    df=df_train,
    models_dict=all_logistic_models_dict_c,
    estimators_dict=estimators_dict,
    target=target,
    n_splits=10,
    random_state=42,
    scale_numeric=True
)

cv_comparison_sorted = (
    cv_comparison
    .sort_values(
        by=["F1_Mean", "Recall_Mean", "AUC_Mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

cv_comparison_sorted

,Variable_Set,Model,Accuracy_Mean,Accuracy_Std,Precision_Mean,Precision_Std,Recall_Mean,Recall_Std,F1_Mean,F1_Std,AUC_Mean,AUC_Std,N_Numeric_Variables,N_Categorical_Variables,N_Features_After_Dummies
0,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.783,0.038,0.410,0.061,0.758,0.107,0.531,0.071,0.847,0.069,7,11,43
1,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.880,0.022,0.738,0.138,0.422,0.112,0.526,0.105,0.856,0.067,7,11,43
2,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.748,0.027,0.360,0.032,0.716,0.102,0.478,0.044,0.813,0.068,3,8,25
3,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.744,0.048,0.358,0.064,0.721,0.140,0.477,0.083,0.796,0.074,0,8,22
4,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.726,0.044,0.342,0.046,0.733,0.102,0.464,0.053,0.783,0.071,5,6,20
5,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.741,0.029,0.348,0.049,0.704,0.152,0.464,0.075,0.790,0.073,0,9,24
6,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.729,0.042,0.338,0.065,0.721,0.163,0.459,0.092,0.791,0.075,4,6,19
7,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.734,0.054,0.347,0.057,0.692,0.100,0.459,0.059,0.795,0.066,0,9,24
8,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.735,0.028,0.341,0.043,0.703,0.132,0.458,0.066,0.791,0.072,3,8,24
9,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.726,0.058,0.339,0.077,0.697,0.109,0.455,0.089,0.789,0.056,0,8,26
10,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.728,0.046,0.337,0.060,0.697,0.116,0.454,0.076,0.798,0.054,3,7,26
11,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.721,0.055,0.334,0.066,0.692,0.106,0.448,0.071,0.779,0.066,0,8,22
12,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.713,0.054,0.327,0.066,0.703,0.124,0.444,0.077,0.779,0.071,4,6,19
13,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.720,0.047,0.328,0.053,0.679,0.112,0.440,0.066,0.777,0.075,0,8,21
14,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.697,0.043,0.307,0.056,0.696,0.132,0.425,0.074,0.748,0.066,3,6,18
15,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.691,0.044,0.299,0.045,0.672,0.124,0.412,0.058,0.741,0.066,0,7,18
16,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.866,0.018,0.761,0.181,0.271,0.092,0.388,0.099,0.816,0.068,3,8,25
17,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.861,0.029,0.729,0.241,0.271,0.081,0.387,0.103,0.799,0.067,0,9,24
18,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.862,0.024,0.698,0.211,0.271,0.081,0.387,0.108,0.796,0.074,0,8,22
19,Modelo 1 — Função Profissional Misto,Logistic Regression,0.864,0.025,0.694,0.186,0.266,0.112,0.378,0.140,0.801,0.057,3,7,26
20,Modelo 1 — Função Profissional,Logistic Regression,0.859,0.022,0.677,0.188,0.223,0.099,0.331,0.134,0.793,0.058,0,8,26
21,Modelo 4 — Experiência Profissional,Logistic Regression,0.856,0.026,0.692,0.243,0.222,0.086,0.331,0.117,0.792,0.075,4,6,19
22,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression,0.852,0.019,0.657,0.187,0.223,0.040,0.329,0.059,0.799,0.073,3,8,24
23,Modelo 3 — Faixa Salarial,Logistic Regression,0.855,0.021,0.681,0.198,0.211,0.080,0.316,0.105,0.778,0.075,0,8,21
24,Modelo 2 — Nível Hierárquico,Logistic Regression,0.855,0.019,0.713,0.204,0.205,0.047,0.314,0.066,0.780,0.067,0,8,22
25,Modelo 6 — Perfil Pessoal,Logistic Regression,0.851,0.019,0.650,0.193,0.205,0.041,0.309,0.065,0.792,0.077,0,9,24
26,Modelo 5 — Antiguidade Organizacional,Logistic Regression,0.854,0.021,0.726,0.214,0.200,0.074,0.302,0.095,0.783,0.071,5,6,20
27,Modelo 3 — Rendimento Quantitativo,Logistic Regression,0.857,0.016,0.749,0.196,0.187,0.067,0.293,0.092,0.780,0.070,4,6,19
28,Modelo 7 — Reduzido Conservador Misto,Logistic Regression,0.846,0.020,0.685,0.322,0.127,0.070,0.206,0.100,0.744,0.068,3,6,18
29,Modelo 7 — Reduzido Conservador,Logistic Regression,0.841,0.024,0.625,0.310,0.121,0.068,0.195,0.097,0.736,0.070,0,7,18

In [20]:
gap_analysis = run_logistic_gap_analysis(
    df=df_train,
    models_dict=all_logistic_models_dict_c,
    estimators_dict=estimators_dict,
    target=target,
    n_splits=10,
    random_state=42,
    scale_numeric=True
)

gap_analysis_sorted = (
    gap_analysis
    .sort_values(
        by=["CV_F1_Mean", "CV_Recall_Mean", "CV_AUC_Mean"],
        ascending=False
    )
    .reset_index(drop=True)
)

gap_analysis_sorted

,Variable_Set,Model,Train_F1_Mean,CV_F1_Mean,F1_Gap,Train_Recall_Mean,CV_Recall_Mean,Recall_Gap,Train_AUC_Mean,CV_AUC_Mean,AUC_Gap,Gap_Diagnosis,N_Numeric_Variables,N_Categorical_Variables,N_Features_After_Dummies
0,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.571,0.531,0.041,0.823,0.758,0.065,0.893,0.847,0.046,Stable generalization,7,11,43
1,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.606,0.526,0.080,0.483,0.422,0.062,0.890,0.856,0.033,Moderate gap,7,11,43
2,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.515,0.478,0.037,0.780,0.716,0.064,0.840,0.813,0.027,Stable generalization,3,8,25
3,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.507,0.477,0.030,0.762,0.721,0.041,0.827,0.796,0.031,Stable generalization,0,8,22
4,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.480,0.464,0.016,0.760,0.733,0.027,0.811,0.783,0.028,Stable generalization,5,6,20
5,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.504,0.464,0.040,0.757,0.704,0.053,0.825,0.790,0.035,Stable generalization,0,9,24
6,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.492,0.459,0.034,0.765,0.721,0.044,0.814,0.791,0.023,Stable generalization,4,6,19
7,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.508,0.459,0.049,0.762,0.692,0.070,0.832,0.795,0.037,Stable generalization,0,9,24
8,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.500,0.458,0.041,0.756,0.703,0.053,0.828,0.791,0.037,Stable generalization,3,8,24
9,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.482,0.455,0.027,0.740,0.697,0.043,0.831,0.789,0.042,Stable generalization,0,8,26
10,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.495,0.454,0.041,0.758,0.697,0.061,0.836,0.798,0.038,Stable generalization,3,7,26
11,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.468,0.448,0.020,0.722,0.692,0.031,0.808,0.779,0.029,Stable generalization,0,8,22
12,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.471,0.444,0.027,0.751,0.703,0.048,0.801,0.779,0.022,Stable generalization,4,6,19
13,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.475,0.440,0.035,0.731,0.679,0.052,0.807,0.777,0.030,Stable generalization,0,8,21
14,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.438,0.425,0.013,0.718,0.696,0.021,0.772,0.748,0.024,Stable generalization,3,6,18
15,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.435,0.412,0.023,0.717,0.672,0.044,0.769,0.741,0.028,Stable generalization,0,7,18
16,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.420,0.388,0.032,0.292,0.271,0.021,0.839,0.816,0.022,Stable generalization,3,8,25
17,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.447,0.387,0.060,0.322,0.271,0.051,0.830,0.799,0.031,Moderate gap,0,9,24
18,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.424,0.387,0.037,0.298,0.271,0.027,0.824,0.796,0.028,Stable generalization,0,8,22
19,Modelo 1 — Função Profissional Misto,Logistic Regression,0.398,0.378,0.019,0.270,0.266,0.004,0.832,0.801,0.031,Possible underfitting,3,7,26
20,Modelo 1 — Função Profissional,Logistic Regression,0.377,0.331,0.046,0.252,0.223,0.029,0.828,0.793,0.034,Possible underfitting,0,8,26
21,Modelo 4 — Experiência Profissional,Logistic Regression,0.376,0.331,0.045,0.252,0.222,0.030,0.812,0.792,0.021,Possible underfitting,4,6,19
22,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression,0.378,0.329,0.049,0.259,0.223,0.036,0.825,0.799,0.026,Possible underfitting,3,8,24
23,Modelo 3 — Faixa Salarial,Logistic Regression,0.352,0.316,0.036,0.234,0.211,0.023,0.804,0.778,0.026,Possible underfitting,0,8,21
24,Modelo 2 — Nível Hierárquico,Logistic Regression,0.346,0.314,0.032,0.224,0.205,0.019,0.805,0.780,0.026,Possible underfitting,0,8,22
25,Modelo 6 — Perfil Pessoal,Logistic Regression,0.375,0.309,0.065,0.252,0.205,0.047,0.822,0.792,0.030,Possible underfitting,0,9,24
26,Modelo 5 — Antiguidade Organizacional,Logistic Regression,0.343,0.302,0.041,0.225,0.200,0.025,0.807,0.783,0.024,Possible underfitting,5,6,20
27,Modelo 3 — Rendimento Quantitativo,Logistic Regression,0.334,0.293,0.041,0.214,0.187,0.027,0.798,0.780,0.018,Possible underfitting,4,6,19
28,Modelo 7 — Reduzido Conservador Misto,Logistic Regression,0.248,0.206,0.043,0.153,0.127,0.025,0.768,0.744,0.024,Possible underfitting,3,6,18
29,Modelo 7 — Reduzido Conservador,Logistic Regression,0.210,0.195,0.014,0.127,0.121,0.006,0.765,0.736,0.028,Possible underfitting,0,7,18

In [21]:
general_results, threshold_results, confusion_results, trained_models, interpretation_results = run_logistic_model_comparison(
    df=df_train,
    models_dict=all_logistic_models_dict_c,
    estimators_dict=estimators_dict,
    target=target,
    thresholds=np.arange(0.20, 0.651, 0.025),
    test_size=0.30,
    random_state=42,
    scale_numeric=True
)

general_results_sorted = (
    general_results
    .sort_values(
        by=["F1-score", "Recall", "AUC"],
        ascending=False
    )
    .reset_index(drop=True)
)

general_results_sorted

,Variable_Set,Model,Threshold,Accuracy,Precision,Recall,F1-score,AUC,N_Numeric_Variables,N_Categorical_Variables,N_Features_After_Dummies
0,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.5,0.809,0.446,0.74,0.556,0.823,7,11,43
1,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.5,0.764,0.384,0.76,0.510,0.808,3,8,25
2,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.5,0.751,0.361,0.70,0.476,0.786,3,8,24
3,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.5,0.741,0.347,0.68,0.459,0.782,0,8,22
4,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.5,0.741,0.347,0.68,0.459,0.774,0,9,24
5,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.5,0.751,0.348,0.62,0.446,0.779,3,7,26
6,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.5,0.741,0.340,0.64,0.444,0.770,0,8,26
7,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.5,0.722,0.327,0.68,0.442,0.771,4,6,19
8,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.5,0.861,0.630,0.34,0.442,0.834,7,11,43
9,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.5,0.709,0.318,0.70,0.438,0.768,0,8,22
10,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.5,0.735,0.333,0.64,0.438,0.781,0,9,24
11,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.5,0.706,0.315,0.70,0.435,0.758,5,6,20
12,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.5,0.722,0.324,0.66,0.434,0.759,0,8,21
13,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.5,0.722,0.324,0.66,0.434,0.748,4,6,19
14,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.5,0.702,0.312,0.70,0.432,0.747,3,6,18
15,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.5,0.689,0.287,0.62,0.392,0.733,0,7,18
16,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.5,0.858,0.636,0.28,0.389,0.789,0,9,24
17,Modelo 6 — Perfil Pessoal,Logistic Regression,0.5,0.861,0.733,0.22,0.338,0.781,0,9,24
18,Modelo 1 — Função Profissional Misto,Logistic Regression,0.5,0.858,0.688,0.22,0.333,0.782,3,7,26
19,Modelo 1 — Função Profissional,Logistic Regression,0.5,0.858,0.714,0.20,0.312,0.772,0,8,26
20,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.5,0.854,0.667,0.20,0.308,0.789,0,8,22
21,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.5,0.848,0.588,0.20,0.299,0.808,3,8,25
22,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression,0.5,0.848,0.588,0.20,0.299,0.793,3,8,24
23,Modelo 3 — Faixa Salarial,Logistic Regression,0.5,0.841,0.526,0.20,0.290,0.769,0,8,21
24,Modelo 3 — Rendimento Quantitativo,Logistic Regression,0.5,0.838,0.500,0.20,0.286,0.747,4,6,19
25,Modelo 7 — Reduzido Conservador Misto,Logistic Regression,0.5,0.851,0.667,0.16,0.258,0.750,3,6,18
26,Modelo 7 — Reduzido Conservador,Logistic Regression,0.5,0.848,0.615,0.16,0.254,0.735,0,7,18
27,Modelo 4 — Experiência Profissional,Logistic Regression,0.5,0.825,0.409,0.18,0.250,0.772,4,6,19
28,Modelo 2 — Nível Hierárquico,Logistic Regression,0.5,0.845,0.571,0.16,0.250,0.773,0,8,22
29,Modelo 5 — Antiguidade Organizacional,Logistic Regression,0.5,0.822,0.333,0.10,0.154,0.757,5,6,20

In [22]:
top_combinations = (
    cv_comparison_sorted
    .head(20)[["Variable_Set", "Model"]]
    .to_dict("records")
)

top_combinations

[{'Variable_Set': 'Modelo 8 — Integrado Multidimensional',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 8 — Integrado Multidimensional',
  'Model': 'Logistic Regression'},
 {'Variable_Set': 'Modelo 2 — Nível Hierárquico e Benefícios',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 4 — Trajetória Organizacional',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 5 — Antiguidade Organizacional',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 6 — Perfil Pessoal',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 4 — Experiência Profissional',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 5 — Estabilidade e Benefícios',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 6 — Perfil Pessoal e Condições de Trabalho',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 1 — Função Profissional',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 1 — Função Profissional Misto',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 2 — Nível Hierárquico',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 3 — Rendimento Quantitativo',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 3 — Faixa Salarial',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 7 — Reduzido Conservador Misto',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 7 — Reduzido Conservador',
  'Model': 'Logistic Regression Balanced'},
 {'Variable_Set': 'Modelo 2 — Nível Hierárquico e Benefícios',
  'Model': 'Logistic Regression'},
 {'Variable_Set': 'Modelo 5 — Estabilidade e Benefícios',
  'Model': 'Logistic Regression'},
 {'Variable_Set': 'Modelo 4 — Trajetória Organizacional',
  'Model': 'Logistic Regression'},
 {'Variable_Set': 'Modelo 1 — Função Profissional Misto',
  'Model': 'Logistic Regression'}]

In [23]:
tuning_results_df, best_models = tune_logistic_hyperparameters_top_combinations(
    df=df_train,
    models_dict=all_logistic_models_dict_c,
    estimators_dict=estimators_dict,
    param_distributions_dict=param_distributions_dict,
    top_combinations=top_combinations,
    target=target,
    n_iter=30,
    n_splits=10,
    scoring="f1",
    random_state=42,
    scale_numeric=True
)

tuning_results_sorted = (
    tuning_results_df
    .sort_values(
        by="Best_Score",
        ascending=False
    )
    .reset_index(drop=True)
)

tuning_results_sorted

/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

,Variable_Set,Model,Best_Score,Scoring,Best_Params,N_Parameter_Combinations_Tested,N_Numeric_Variables,N_Categorical_Variables,N_Features_After_Dummies
0,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.542,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,7,11,43
1,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.531,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,7,11,43
2,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.484,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,8,25
3,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.482,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,8,22
4,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.470,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,9,24
5,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.467,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,4,6,19
6,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.465,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,5,6,20
7,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.465,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,9,24
8,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.465,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,8,24
9,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.460,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,8,26
10,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.455,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,7,26
11,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.451,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,8,22
12,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.451,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,4,6,19
13,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.442,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,8,21
14,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.428,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,9,24
15,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.425,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,6,18
16,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.414,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,7,18
17,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.405,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,8,25
18,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.401,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,0,8,22
19,Modelo 1 — Função Profissional Misto,Logistic Regression,0.401,f1,"{'classifier__solver': 'liblinear', 'classifie...",10,3,7,26

In [24]:
(
    threshold_cv_comparison,
    best_thresholds_cv,
    final_test_results_df,
    confusion_results_opt,
    fitted_models,
    interpretation_results_opt
) = evaluate_thresholds_optimized_logistic_models_cv(
    df=df_train,
    df_test=df_test,
    models_dict=all_logistic_models_dict_c,
    best_models=best_models,
    target=target,
    thresholds=np.arange(0.20, 0.751, 0.01),
    test_size=0.30,
    random_state=42,
    n_splits=10,
    threshold_metric="F1-score"
)

best_thresholds_cv

/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/nathansperinde/Desktop/Portifolio/projeto_1/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

,Variable_Set,Model,Threshold,Accuracy,Precision,Recall,F1-score,AUC
1,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.38,0.874,0.615,0.578,0.596,0.853
0,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.64,0.846,0.518,0.681,0.589,0.842
16,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.33,0.848,0.530,0.524,0.527,0.812
2,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.71,0.848,0.532,0.506,0.519,0.807
8,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.59,0.801,0.424,0.651,0.513,0.790
17,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.23,0.807,0.430,0.608,0.504,0.798
7,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.74,0.856,0.568,0.452,0.503,0.791
3,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.57,0.791,0.408,0.651,0.501,0.792
18,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.26,0.824,0.462,0.542,0.499,0.795
5,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.56,0.780,0.394,0.675,0.498,0.786
6,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.61,0.801,0.419,0.608,0.496,0.785
10,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.65,0.816,0.445,0.560,0.496,0.795
19,Modelo 1 — Função Profissional Misto,Logistic Regression,0.31,0.828,0.470,0.524,0.496,0.802
9,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.61,0.800,0.417,0.602,0.493,0.786
4,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.60,0.790,0.401,0.608,0.483,0.778
12,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.65,0.815,0.439,0.524,0.478,0.770
11,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.62,0.795,0.404,0.572,0.474,0.772
13,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.58,0.785,0.391,0.596,0.473,0.773
14,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.50,0.697,0.307,0.699,0.426,0.740
15,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.51,0.698,0.304,0.675,0.419,0.714

In [25]:
final_test_results_sorted = (
    final_test_results_df
    .sort_values(
        by=["F1-score", "Recall", "AUC"],
        ascending=False
    )
    .reset_index(drop=True)
)

final_test_results_sorted

,Variable_Set,Model,Threshold,Accuracy,Precision,Recall,F1-score,AUC
0,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.38,0.864,0.575,0.592,0.583,0.814
1,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.71,0.864,0.582,0.549,0.565,0.830
2,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.64,0.837,0.495,0.634,0.556,0.810
3,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.33,0.853,0.543,0.535,0.539,0.833
4,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.58,0.810,0.437,0.634,0.517,0.797
5,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.62,0.823,0.461,0.577,0.512,0.817
6,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.59,0.816,0.447,0.592,0.509,0.802
7,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.61,0.821,0.456,0.577,0.509,0.796
8,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.60,0.807,0.430,0.606,0.503,0.781
9,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.56,0.794,0.407,0.620,0.492,0.802
10,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.23,0.791,0.404,0.620,0.489,0.795
11,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.65,0.819,0.447,0.535,0.487,0.796
12,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.61,0.803,0.415,0.549,0.473,0.781
13,Modelo 1 — Função Profissional Misto,Logistic Regression,0.31,0.830,0.471,0.465,0.468,0.788
14,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.74,0.857,0.587,0.380,0.462,0.795
15,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.65,0.819,0.442,0.479,0.459,0.780
16,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.26,0.810,0.422,0.493,0.455,0.780
17,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.51,0.728,0.331,0.676,0.444,0.756
18,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.50,0.735,0.333,0.648,0.440,0.781
19,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.57,0.766,0.349,0.521,0.418,0.771

In [26]:
final_summary = (
    final_test_results_sorted
    .merge(
        tuning_results_sorted[
            ["Variable_Set", "Model", "Best_Score", "Best_Params"]
        ],
        on=["Variable_Set", "Model"],
        how="left"
    )
    .merge(
        gap_analysis_sorted[
            [
                "Variable_Set",
                "Model",
                "Train_F1_Mean",
                "CV_F1_Mean",
                "F1_Gap",
                "Train_Recall_Mean",
                "CV_Recall_Mean",
                "Recall_Gap",
                "Gap_Diagnosis"
            ]
        ],
        on=["Variable_Set", "Model"],
        how="left"
    )
)

final_summary

,Variable_Set,Model,Threshold,Accuracy,Precision,Recall,F1-score,AUC,Best_Score,Best_Params,Train_F1_Mean,CV_F1_Mean,F1_Gap,Train_Recall_Mean,CV_Recall_Mean,Recall_Gap,Gap_Diagnosis
0,Modelo 8 — Integrado Multidimensional,Logistic Regression,0.38,0.864,0.575,0.592,0.583,0.814,0.542,"{'classifier__solver': 'liblinear', 'classifie...",0.606,0.526,0.080,0.483,0.422,0.062,Moderate gap
1,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression Balanced,0.71,0.864,0.582,0.549,0.565,0.830,0.484,"{'classifier__solver': 'liblinear', 'classifie...",0.515,0.478,0.037,0.780,0.716,0.064,Stable generalization
2,Modelo 8 — Integrado Multidimensional,Logistic Regression Balanced,0.64,0.837,0.495,0.634,0.556,0.810,0.531,"{'classifier__solver': 'liblinear', 'classifie...",0.571,0.531,0.041,0.823,0.758,0.065,Stable generalization
3,Modelo 2 — Nível Hierárquico e Benefícios,Logistic Regression,0.33,0.853,0.543,0.535,0.539,0.833,0.405,"{'classifier__solver': 'liblinear', 'classifie...",0.420,0.388,0.032,0.292,0.271,0.021,Stable generalization
4,Modelo 3 — Faixa Salarial,Logistic Regression Balanced,0.58,0.810,0.437,0.634,0.517,0.797,0.442,"{'classifier__solver': 'liblinear', 'classifie...",0.475,0.440,0.035,0.731,0.679,0.052,Stable generalization
5,Modelo 2 — Nível Hierárquico,Logistic Regression Balanced,0.62,0.823,0.461,0.577,0.512,0.817,0.451,"{'classifier__solver': 'liblinear', 'classifie...",0.468,0.448,0.020,0.722,0.692,0.031,Stable generalization
6,Modelo 6 — Perfil Pessoal e Condições de Trabalho,Logistic Regression Balanced,0.59,0.816,0.447,0.592,0.509,0.802,0.465,"{'classifier__solver': 'liblinear', 'classifie...",0.500,0.458,0.041,0.756,0.703,0.053,Stable generalization
7,Modelo 4 — Experiência Profissional,Logistic Regression Balanced,0.61,0.821,0.456,0.577,0.509,0.796,0.467,"{'classifier__solver': 'liblinear', 'classifie...",0.492,0.459,0.034,0.765,0.721,0.044,Stable generalization
8,Modelo 5 — Antiguidade Organizacional,Logistic Regression Balanced,0.60,0.807,0.430,0.606,0.503,0.781,0.465,"{'classifier__solver': 'liblinear', 'classifie...",0.480,0.464,0.016,0.760,0.733,0.027,Stable generalization
9,Modelo 6 — Perfil Pessoal,Logistic Regression Balanced,0.56,0.794,0.407,0.620,0.492,0.802,0.470,"{'classifier__solver': 'liblinear', 'classifie...",0.504,0.464,0.040,0.757,0.704,0.053,Stable generalization
10,Modelo 5 — Estabilidade e Benefícios,Logistic Regression,0.23,0.791,0.404,0.620,0.489,0.795,0.428,"{'classifier__solver': 'liblinear', 'classifie...",0.447,0.387,0.060,0.322,0.271,0.051,Moderate gap
11,Modelo 3 — Rendimento Quantitativo,Logistic Regression Balanced,0.65,0.819,0.447,0.535,0.487,0.796,0.451,"{'classifier__solver': 'liblinear', 'classifie...",0.471,0.444,0.027,0.751,0.703,0.048,Stable generalization
12,Modelo 1 — Função Profissional,Logistic Regression Balanced,0.61,0.803,0.415,0.549,0.473,0.781,0.460,"{'classifier__solver': 'liblinear', 'classifie...",0.482,0.455,0.027,0.740,0.697,0.043,Stable generalization
13,Modelo 1 — Função Profissional Misto,Logistic Regression,0.31,0.830,0.471,0.465,0.468,0.788,0.401,"{'classifier__solver': 'liblinear', 'classifie...",0.398,0.378,0.019,0.270,0.266,0.004,Possible underfitting
14,Modelo 5 — Estabilidade e Benefícios,Logistic Regression Balanced,0.74,0.857,0.587,0.380,0.462,0.795,0.465,"{'classifier__solver': 'liblinear', 'classifie...",0.508,0.459,0.049,0.762,0.692,0.070,Stable generalization
15,Modelo 1 — Função Profissional Misto,Logistic Regression Balanced,0.65,0.819,0.442,0.479,0.459,0.780,0.455,"{'classifier__solver': 'liblinear', 'classifie...",0.495,0.454,0.041,0.758,0.697,0.061,Stable generalization
16,Modelo 4 — Trajetória Organizacional,Logistic Regression,0.26,0.810,0.422,0.493,0.455,0.780,0.401,"{'classifier__solver': 'liblinear', 'classifie...",0.424,0.387,0.037,0.298,0.271,0.027,Stable generalization
17,Modelo 7 — Reduzido Conservador,Logistic Regression Balanced,0.51,0.728,0.331,0.676,0.444,0.756,0.414,"{'classifier__solver': 'liblinear', 'classifie...",0.435,0.412,0.023,0.717,0.672,0.044,Stable generalization
18,Modelo 7 — Reduzido Conservador Misto,Logistic Regression Balanced,0.50,0.735,0.333,0.648,0.440,0.781,0.425,"{'classifier__solver': 'liblinear', 'classifie...",0.438,0.425,0.013,0.718,0.696,0.021,Stable generalization
19,Modelo 4 — Trajetória Organizacional,Logistic Regression Balanced,0.57,0.766,0.349,0.521,0.418,0.771,0.482,"{'classifier__solver': 'liblinear', 'classifie...",0.507,0.477,0.030,0.762,0.721,0.041,Stable generalization

In [48]:
for i in range(0, 20):

    best_models = final_summary.iloc[i]

    if best_models["Variable_Set"] == "Modelo 8 — Integrado Multidimensional":
        continue

    print("Variable set:", best_models["Variable_Set"])
    print("Model:", best_models["Model"])
    print("Best threshold:", best_models["Threshold"])

    confusion_mat = confusion_results_opt[
        (best_models["Variable_Set"], best_models["Model"])
    ]

    interpretation = interpretation_results_opt[
        (best_models["Variable_Set"], best_models["Model"])
    ]

    top_positive_odds = (
        interpretation
        .sort_values("Odds_Ratio", ascending=False)
        .head(20)
        .reset_index(drop=True)
    )

    top_negative_odds = (
        interpretation
        .sort_values("Odds_Ratio", ascending=True)
        .head(20)
        .reset_index(drop=True)
    )

    display(best_models)

    display(interpretation)

    display(confusion_mat)

    print("\n\n")

Variable set: Modelo 2 — Nível Hierárquico e Benefícios
Model: Logistic Regression Balanced
Best threshold: 0.71

Variable_Set                 Modelo 2 — Nível Hierárquico e Benefícios
Model                                     Logistic Regression Balanced
Threshold                                                         0.71
Accuracy                                                         0.864
Precision                                                        0.582
Recall                                                           0.549
F1-score                                                         0.565
AUC                                                               0.83
Best_Score                                                       0.484
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.515
CV_F1_Mean                                                       0.478
F1_Gap                                                           0.037
Train_Recall_Mean                                                 0.78
CV_Recall_Mean                                                   0.716
Recall_Gap                                                       0.064
Gap_Diagnosis                                    Stable generalization
Name: 1, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.519700    4.570854
1                             OverTime_Yes     1.448745    4.257766
2                  JobInvolvementLevel_Low     1.406853    4.083084
3             BusinessTravel_Travel_Rarely     0.837211    2.309917
4         EnvironmentSatisfactionLevel_Low     0.785172    2.192784
5                   StockOption_No Options     0.549700    1.732732
6                    SatisfactionLevel_Low     0.413862    1.512649
7                 SatisfactionLevel_Medium     0.304365    1.355763
8                         DistanceFromHome     0.281086    1.324568
9               JobInvolvementLevel_Medium     0.061730    1.063675
10                   TrainingTimesLastYear    -0.093470    0.910765
11     EnvironmentSatisfactionLevel_Medium    -0.136196    0.872671
12                               DailyRate    -0.166737    0.846422
13  EnvironmentSatisfactionLevel_Very High    -0.219148    0.803203
14           JobInvolvementLevel_Very High    -0.284181    0.752631
15                      StockOption_Medium    -0.510931    0.599937
16             SatisfactionLevel_Very High    -0.522326    0.593139
17               WorkLifeBalanceLevel_Best    -0.564504    0.568642
18               WorkLifeBalanceLevel_Good    -0.632286    0.531376
19                 JobLevelGroup_Mid Level    -0.743093    0.475640
20                         StockOption_Low    -0.823602    0.438848
21              JobLevelGroup_Junior Level    -1.282693    0.277290
22             WorkLifeBalanceLevel_Better    -1.321100    0.266842
23           JobLevelGroup_Executive Level    -1.838839    0.159002
24              JobLevelGroup_Senior Level    -2.148339    0.116678

array([[342,  28],
       [ 32,  39]])

Variable set: Modelo 2 — Nível Hierárquico e Benefícios
Model: Logistic Regression
Best threshold: 0.33

Variable_Set                 Modelo 2 — Nível Hierárquico e Benefícios
Model                                              Logistic Regression
Threshold                                                         0.33
Accuracy                                                         0.853
Precision                                                        0.543
Recall                                                           0.535
F1-score                                                         0.539
AUC                                                              0.833
Best_Score                                                       0.405
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                     0.42
CV_F1_Mean                                                       0.388
F1_Gap                                                           0.032
Train_Recall_Mean                                                0.292
CV_Recall_Mean                                                   0.271
Recall_Gap                                                       0.021
Gap_Diagnosis                                    Stable generalization
Name: 3, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  JobInvolvementLevel_Low     1.553291    4.727002
1                             OverTime_Yes     1.527750    4.607799
2         BusinessTravel_Travel_Frequently     1.489760    4.436032
3         EnvironmentSatisfactionLevel_Low     0.875525    2.400135
4                   StockOption_No Options     0.800200    2.225986
5             BusinessTravel_Travel_Rarely     0.782154    2.186176
6                    SatisfactionLevel_Low     0.411320    1.508808
7                 SatisfactionLevel_Medium     0.339562    1.404332
8                         DistanceFromHome     0.292749    1.340106
9               JobInvolvementLevel_Medium     0.134231    1.143658
10     EnvironmentSatisfactionLevel_Medium    -0.102873    0.902241
11                   TrainingTimesLastYear    -0.143265    0.866524
12                               DailyRate    -0.202725    0.816503
13  EnvironmentSatisfactionLevel_Very High    -0.266672    0.765924
14                      StockOption_Medium    -0.399671    0.670540
15           JobInvolvementLevel_Very High    -0.419274    0.657524
16             SatisfactionLevel_Very High    -0.582052    0.558751
17                         StockOption_Low    -0.615040    0.540619
18               WorkLifeBalanceLevel_Best    -0.691765    0.500692
19               WorkLifeBalanceLevel_Good    -0.752100    0.471375
20                 JobLevelGroup_Mid Level    -0.929894    0.394595
21             WorkLifeBalanceLevel_Better    -1.338352    0.262278
22              JobLevelGroup_Junior Level    -1.373116    0.253316
23           JobLevelGroup_Executive Level    -2.095017    0.123068
24              JobLevelGroup_Senior Level    -2.152110    0.116239

array([[338,  32],
       [ 33,  38]])

Variable set: Modelo 3 — Faixa Salarial
Model: Logistic Regression Balanced
Best threshold: 0.58

Variable_Set                                 Modelo 3 — Faixa Salarial
Model                                     Logistic Regression Balanced
Threshold                                                         0.58
Accuracy                                                          0.81
Precision                                                        0.437
Recall                                                           0.634
F1-score                                                         0.517
AUC                                                              0.797
Best_Score                                                       0.442
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.475
CV_F1_Mean                                                        0.44
F1_Gap                                                           0.035
Train_Recall_Mean                                                0.731
CV_Recall_Mean                                                   0.679
Recall_Gap                                                       0.052
Gap_Diagnosis                                    Stable generalization
Name: 4, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  JobInvolvementLevel_Low     1.487784    4.427274
1                             OverTime_Yes     1.425059    4.158102
2         BusinessTravel_Travel_Frequently     1.354524    3.874914
3                          IncomeGroup_Low     1.076480    2.934334
4         EnvironmentSatisfactionLevel_Low     0.921115    2.512091
5             BusinessTravel_Travel_Rarely     0.808492    2.244521
6                      DistanceGroup_21-30     0.552475    1.737549
7                    SatisfactionLevel_Low     0.492776    1.636853
8                      DistanceGroup_11-20     0.379844    1.462057
9                 SatisfactionLevel_Medium     0.210319    1.234071
10              JobInvolvementLevel_Medium     0.182869    1.200657
11                      DistanceGroup_6-10     0.048184    1.049364
12     EnvironmentSatisfactionLevel_Medium    -0.114768    0.891573
13                      IncomeGroup_Medium    -0.202133    0.816987
14           JobInvolvementLevel_Very High    -0.205955    0.813870
15  EnvironmentSatisfactionLevel_Very High    -0.217322    0.804671
16             SatisfactionLevel_Very High    -0.605674    0.545706
17               WorkLifeBalanceLevel_Best    -0.694431    0.499358
18                   IncomeGroup_Very High    -0.739501    0.477352
19               WorkLifeBalanceLevel_Good    -0.804485    0.447318
20             WorkLifeBalanceLevel_Better    -1.383678    0.250655

array([[312,  58],
       [ 26,  45]])

Variable set: Modelo 2 — Nível Hierárquico
Model: Logistic Regression Balanced
Best threshold: 0.62

Variable_Set                              Modelo 2 — Nível Hierárquico
Model                                     Logistic Regression Balanced
Threshold                                                         0.62
Accuracy                                                         0.823
Precision                                                        0.461
Recall                                                           0.577
F1-score                                                         0.512
AUC                                                              0.817
Best_Score                                                       0.451
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.468
CV_F1_Mean                                                       0.448
F1_Gap                                                            0.02
Train_Recall_Mean                                                0.722
CV_Recall_Mean                                                   0.692
Recall_Gap                                                       0.031
Gap_Diagnosis                                    Stable generalization
Name: 5, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  JobInvolvementLevel_Low     1.389424    4.012537
1                             OverTime_Yes     1.328163    3.774102
2         BusinessTravel_Travel_Frequently     1.189844    3.286569
3         EnvironmentSatisfactionLevel_Low     0.801552    2.228997
4                      DistanceGroup_21-30     0.575941    1.778803
5             BusinessTravel_Travel_Rarely     0.570836    1.769746
6                      DistanceGroup_11-20     0.458965    1.582435
7                    SatisfactionLevel_Low     0.362813    1.437367
8                 SatisfactionLevel_Medium     0.233008    1.262392
9               JobInvolvementLevel_Medium     0.147070    1.158435
10                      DistanceGroup_6-10     0.020880    1.021100
11     EnvironmentSatisfactionLevel_Medium    -0.057767    0.943870
12           JobInvolvementLevel_Very High    -0.131443    0.876829
13  EnvironmentSatisfactionLevel_Very High    -0.173675    0.840570
14               WorkLifeBalanceLevel_Best    -0.443728    0.641640
15               WorkLifeBalanceLevel_Good    -0.514869    0.597579
16             SatisfactionLevel_Very High    -0.593488    0.552397
17                 JobLevelGroup_Mid Level    -0.702504    0.495344
18             WorkLifeBalanceLevel_Better    -1.098368    0.333415
19              JobLevelGroup_Junior Level    -1.195275    0.302621
20           JobLevelGroup_Executive Level    -1.555867    0.211006
21              JobLevelGroup_Senior Level    -1.872983    0.153665

array([[322,  48],
       [ 30,  41]])

Variable set: Modelo 6 — Perfil Pessoal e Condições de Trabalho
Model: Logistic Regression Balanced
Best threshold: 0.59

Variable_Set         Modelo 6 — Perfil Pessoal e Condições de Trabalho
Model                                     Logistic Regression Balanced
Threshold                                                         0.59
Accuracy                                                         0.816
Precision                                                        0.447
Recall                                                           0.592
F1-score                                                         0.509
AUC                                                              0.802
Best_Score                                                       0.465
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                      0.5
CV_F1_Mean                                                       0.458
F1_Gap                                                           0.041
Train_Recall_Mean                                                0.756
CV_Recall_Mean                                                   0.703
Recall_Gap                                                       0.053
Gap_Diagnosis                                    Stable generalization
Name: 6, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.709460    5.525979
1                  JobInvolvementLevel_Low     1.517495    4.560786
2                             OverTime_Yes     1.465581    4.330057
3             BusinessTravel_Travel_Rarely     1.021356    2.776956
4                     MaritalStatus_Single     1.010921    2.748130
5         EnvironmentSatisfactionLevel_Low     0.750307    2.117650
6                    SatisfactionLevel_Low     0.548906    1.731358
7                 SatisfactionLevel_Medium     0.273279    1.314267
8                         DistanceFromHome     0.272066    1.312674
9                    MaritalStatus_Married     0.117872    1.125100
10              JobInvolvementLevel_Medium     0.077935    1.081053
11                               DailyRate    -0.110242    0.895617
12                   TrainingTimesLastYear    -0.132975    0.875487
13     EnvironmentSatisfactionLevel_Medium    -0.301833    0.739462
14           JobInvolvementLevel_Very High    -0.316995    0.728334
15  EnvironmentSatisfactionLevel_Very High    -0.412570    0.661947
16             SatisfactionLevel_Very High    -0.504477    0.603821
17               WorkLifeBalanceLevel_Best    -0.818610    0.441044
18               WorkLifeBalanceLevel_Good    -0.828544    0.436685
19                          AgeGroup_26-35    -1.080457    0.339440
20             WorkLifeBalanceLevel_Better    -1.487796    0.225870
21                          AgeGroup_46-55    -1.579271    0.206125
22                          AgeGroup_56-65    -1.827524    0.160811
23                          AgeGroup_36-45    -2.084077    0.124422

array([[318,  52],
       [ 29,  42]])

Variable set: Modelo 4 — Experiência Profissional
Model: Logistic Regression Balanced
Best threshold: 0.61

Variable_Set                       Modelo 4 — Experiência Profissional
Model                                     Logistic Regression Balanced
Threshold                                                         0.61
Accuracy                                                         0.821
Precision                                                        0.456
Recall                                                           0.577
F1-score                                                         0.509
AUC                                                              0.796
Best_Score                                                       0.467
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.492
CV_F1_Mean                                                       0.459
F1_Gap                                                           0.034
Train_Recall_Mean                                                0.765
CV_Recall_Mean                                                   0.721
Recall_Gap                                                       0.044
Gap_Diagnosis                                    Stable generalization
Name: 7, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.609731    5.001464
1                  JobInvolvementLevel_Low     1.515689    4.552559
2                             OverTime_Yes     1.493841    4.454171
3             BusinessTravel_Travel_Rarely     0.993029    2.699397
4         EnvironmentSatisfactionLevel_Low     0.833824    2.302106
5                    SatisfactionLevel_Low     0.544504    1.723752
6                 SatisfactionLevel_Medium     0.291623    1.338598
7                         DistanceFromHome     0.228001    1.256086
8               JobInvolvementLevel_Medium     0.187959    1.206784
9            JobInvolvementLevel_Very High    -0.139440    0.869845
10                               DailyRate    -0.160345    0.851850
11                   TrainingTimesLastYear    -0.165671    0.847325
12     EnvironmentSatisfactionLevel_Medium    -0.246835    0.781270
13  EnvironmentSatisfactionLevel_Very High    -0.274206    0.760175
14             SatisfactionLevel_Very High    -0.541360    0.581956
15               WorkLifeBalanceLevel_Best    -0.662011    0.515813
16                       TotalWorkingYears    -0.742185    0.476072
17               WorkLifeBalanceLevel_Good    -0.758657    0.468295
18             WorkLifeBalanceLevel_Better    -1.382317    0.250996

array([[321,  49],
       [ 30,  41]])

Variable set: Modelo 5 — Antiguidade Organizacional
Model: Logistic Regression Balanced
Best threshold: 0.6

Variable_Set                     Modelo 5 — Antiguidade Organizacional
Model                                     Logistic Regression Balanced
Threshold                                                          0.6
Accuracy                                                         0.807
Precision                                                         0.43
Recall                                                           0.606
F1-score                                                         0.503
AUC                                                              0.781
Best_Score                                                       0.465
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                     0.48
CV_F1_Mean                                                       0.464
F1_Gap                                                           0.016
Train_Recall_Mean                                                 0.76
CV_Recall_Mean                                                   0.733
Recall_Gap                                                       0.027
Gap_Diagnosis                                    Stable generalization
Name: 8, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  JobInvolvementLevel_Low     1.479704    4.391644
1         BusinessTravel_Travel_Frequently     1.428675    4.173168
2                             OverTime_Yes     1.354448    3.874622
3             BusinessTravel_Travel_Rarely     0.763183    2.145094
4         EnvironmentSatisfactionLevel_Low     0.710154    2.034305
5                  YearsSinceLastPromotion     0.412903    1.511198
6                    SatisfactionLevel_Low     0.408821    1.505042
7                 SatisfactionLevel_Medium     0.225673    1.253166
8               JobInvolvementLevel_Medium     0.209353    1.232880
9                         DistanceFromHome     0.185710    1.204073
10           JobInvolvementLevel_Very High    -0.023461    0.976812
11                   TrainingTimesLastYear    -0.107354    0.898208
12                               DailyRate    -0.167899    0.845439
13  EnvironmentSatisfactionLevel_Very High    -0.287493    0.750142
14     EnvironmentSatisfactionLevel_Medium    -0.297918    0.742362
15             SatisfactionLevel_Very High    -0.527353    0.590165
16               WorkLifeBalanceLevel_Best    -0.569356    0.565890
17               WorkLifeBalanceLevel_Good    -0.689230    0.501962
18                          YearsAtCompany    -0.905648    0.404280
19             WorkLifeBalanceLevel_Better    -1.245558    0.287780

array([[313,  57],
       [ 28,  43]])

Variable set: Modelo 6 — Perfil Pessoal
Model: Logistic Regression Balanced
Best threshold: 0.56

Variable_Set                                 Modelo 6 — Perfil Pessoal
Model                                     Logistic Regression Balanced
Threshold                                                         0.56
Accuracy                                                         0.794
Precision                                                        0.407
Recall                                                            0.62
F1-score                                                         0.492
AUC                                                              0.802
Best_Score                                                        0.47
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.504
CV_F1_Mean                                                       0.464
F1_Gap                                                            0.04
Train_Recall_Mean                                                0.757
CV_Recall_Mean                                                   0.704
Recall_Gap                                                       0.053
Gap_Diagnosis                                    Stable generalization
Name: 9, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.642588    5.168531
1                  JobInvolvementLevel_Low     1.515584    4.552080
2                             OverTime_Yes     1.461147    4.310900
3                     MaritalStatus_Single     1.016836    2.764435
4             BusinessTravel_Travel_Rarely     0.955729    2.600565
5         EnvironmentSatisfactionLevel_Low     0.773906    2.168220
6                      DistanceGroup_21-30     0.746416    2.109426
7                      DistanceGroup_11-20     0.565159    1.759728
8                    SatisfactionLevel_Low     0.542087    1.719592
9                 SatisfactionLevel_Medium     0.278556    1.321220
10                      DistanceGroup_6-10     0.169986    1.185289
11              JobInvolvementLevel_Medium     0.104160    1.109778
12                   MaritalStatus_Married     0.097834    1.102780
13     EnvironmentSatisfactionLevel_Medium    -0.266486    0.766066
14           JobInvolvementLevel_Very High    -0.323728    0.723447
15  EnvironmentSatisfactionLevel_Very High    -0.377801    0.685367
16             SatisfactionLevel_Very High    -0.503644    0.604324
17               WorkLifeBalanceLevel_Best    -0.783726    0.456701
18               WorkLifeBalanceLevel_Good    -0.811005    0.444411
19                          AgeGroup_26-35    -1.076110    0.340919
20             WorkLifeBalanceLevel_Better    -1.448064    0.235025
21                          AgeGroup_46-55    -1.551440    0.211943
22                          AgeGroup_56-65    -1.749606    0.173842
23                          AgeGroup_36-45    -2.076992    0.125307

array([[306,  64],
       [ 27,  44]])

Variable set: Modelo 5 — Estabilidade e Benefícios
Model: Logistic Regression
Best threshold: 0.23

Variable_Set                      Modelo 5 — Estabilidade e Benefícios
Model                                              Logistic Regression
Threshold                                                         0.23
Accuracy                                                         0.791
Precision                                                        0.404
Recall                                                            0.62
F1-score                                                         0.489
AUC                                                              0.795
Best_Score                                                       0.428
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.447
CV_F1_Mean                                                       0.387
F1_Gap                                                            0.06
Train_Recall_Mean                                                0.322
CV_Recall_Mean                                                   0.271
Recall_Gap                                                       0.051
Gap_Diagnosis                                             Moderate gap
Name: 10, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  JobInvolvementLevel_Low     1.584274    4.875750
1         BusinessTravel_Travel_Frequently     1.560980    4.763485
2                             OverTime_Yes     1.352532    3.867207
3             BusinessTravel_Travel_Rarely     0.836284    2.307775
4         EnvironmentSatisfactionLevel_Low     0.764020    2.146890
5                      DistanceGroup_21-30     0.639282    1.895119
6                   StockOption_No Options     0.608297    1.837300
7                    SatisfactionLevel_Low     0.576362    1.779553
8                      DistanceGroup_11-20     0.560537    1.751613
9                 SatisfactionLevel_Medium     0.350332    1.419539
10              JobInvolvementLevel_Medium     0.224547    1.251756
11                      DistanceGroup_6-10     0.106000    1.111821
12     EnvironmentSatisfactionLevel_Medium    -0.191932    0.825363
13  EnvironmentSatisfactionLevel_Very High    -0.244370    0.783198
14           JobInvolvementLevel_Very High    -0.403026    0.668295
15             SatisfactionLevel_Very High    -0.476444    0.620988
16               WorkLifeBalanceLevel_Good    -0.747336    0.473627
17                         StockOption_Low    -0.760593    0.467389
18               WorkLifeBalanceLevel_Best    -0.770596    0.462737
19                      StockOption_Medium    -0.819080    0.440837
20                  RoleStabilityGroup_2-3    -1.038331    0.354045
21                  RoleStabilityGroup_4-7    -1.353698    0.258283
22             WorkLifeBalanceLevel_Better    -1.379702    0.251654
23                   RoleStabilityGroup_8+    -2.034586    0.130735

array([[305,  65],
       [ 27,  44]])

Variable set: Modelo 3 — Rendimento Quantitativo
Model: Logistic Regression Balanced
Best threshold: 0.65

Variable_Set                        Modelo 3 — Rendimento Quantitativo
Model                                     Logistic Regression Balanced
Threshold                                                         0.65
Accuracy                                                         0.819
Precision                                                        0.447
Recall                                                           0.535
F1-score                                                         0.487
AUC                                                              0.796
Best_Score                                                       0.451
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.471
CV_F1_Mean                                                       0.444
F1_Gap                                                           0.027
Train_Recall_Mean                                                0.751
CV_Recall_Mean                                                   0.703
Recall_Gap                                                       0.048
Gap_Diagnosis                                    Stable generalization
Name: 11, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.540242    4.665721
1                  JobInvolvementLevel_Low     1.495744    4.462656
2                             OverTime_Yes     1.475096    4.371455
3             BusinessTravel_Travel_Rarely     0.955643    2.600342
4         EnvironmentSatisfactionLevel_Low     0.798795    2.222860
5                    SatisfactionLevel_Low     0.477552    1.612124
6                 SatisfactionLevel_Medium     0.359049    1.431968
7                         DistanceFromHome     0.218488    1.244194
8               JobInvolvementLevel_Medium     0.126639    1.135007
9                    TrainingTimesLastYear    -0.139724    0.869599
10                               DailyRate    -0.169469    0.844113
11           JobInvolvementLevel_Very High    -0.203220    0.816099
12     EnvironmentSatisfactionLevel_Medium    -0.241618    0.785356
13  EnvironmentSatisfactionLevel_Very High    -0.267751    0.765099
14             SatisfactionLevel_Very High    -0.557278    0.572766
15               WorkLifeBalanceLevel_Best    -0.566478    0.567521
16               WorkLifeBalanceLevel_Good    -0.660106    0.516797
17                           MonthlyIncome    -0.667620    0.512928
18             WorkLifeBalanceLevel_Better    -1.265365    0.282136

array([[323,  47],
       [ 33,  38]])

Variable set: Modelo 1 — Função Profissional
Model: Logistic Regression Balanced
Best threshold: 0.61

Variable_Set                            Modelo 1 — Função Profissional
Model                                     Logistic Regression Balanced
Threshold                                                         0.61
Accuracy                                                         0.803
Precision                                                        0.415
Recall                                                           0.549
F1-score                                                         0.473
AUC                                                              0.781
Best_Score                                                        0.46
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.482
CV_F1_Mean                                                       0.455
F1_Gap                                                           0.027
Train_Recall_Mean                                                 0.74
CV_Recall_Mean                                                   0.697
Recall_Gap                                                       0.043
Gap_Diagnosis                                    Stable generalization
Name: 12, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0             JobRole_Sales Representative     2.595975   13.409650
1            JobRole_Laboratory Technician     1.575859    4.834892
2                             OverTime_Yes     1.518651    4.566062
3                  JobRole_Human Resources     1.419009    4.133024
4                  JobInvolvementLevel_Low     1.207941    3.346587
5                  JobRole_Sales Executive     1.159145    3.187208
6         BusinessTravel_Travel_Frequently     1.149366    3.156193
7         EnvironmentSatisfactionLevel_Low     0.820682    2.272049
8             BusinessTravel_Travel_Rarely     0.607714    1.836229
9                      DistanceGroup_21-30     0.563414    1.756659
10              JobRole_Research Scientist     0.491277    1.634402
11                     DistanceGroup_11-20     0.397078    1.487472
12                   SatisfactionLevel_Low     0.357223    1.429355
13                SatisfactionLevel_Medium     0.247933    1.281374
14              JobInvolvementLevel_Medium     0.185923    1.204330
15                      DistanceGroup_6-10     0.000000    1.000000
16          JobRole_Manufacturing Director    -0.031544    0.968948
17  EnvironmentSatisfactionLevel_Very High    -0.175389    0.839131
18           JobInvolvementLevel_Very High    -0.192497    0.824897
19     EnvironmentSatisfactionLevel_Medium    -0.225108    0.798430
20                         JobRole_Manager    -0.456450    0.633529
21               WorkLifeBalanceLevel_Best    -0.545078    0.579797
22             SatisfactionLevel_Very High    -0.642829    0.525803
23               WorkLifeBalanceLevel_Good    -0.671111    0.511140
24             WorkLifeBalanceLevel_Better    -1.240946    0.289111
25               JobRole_Research Director    -1.270832    0.280598

array([[315,  55],
       [ 32,  39]])

Variable set: Modelo 1 — Função Profissional Misto
Model: Logistic Regression
Best threshold: 0.31

Variable_Set                      Modelo 1 — Função Profissional Misto
Model                                              Logistic Regression
Threshold                                                         0.31
Accuracy                                                          0.83
Precision                                                        0.471
Recall                                                           0.465
F1-score                                                         0.468
AUC                                                              0.788
Best_Score                                                       0.401
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.398
CV_F1_Mean                                                       0.378
F1_Gap                                                           0.019
Train_Recall_Mean                                                 0.27
CV_Recall_Mean                                                   0.266
Recall_Gap                                                       0.004
Gap_Diagnosis                                    Possible underfitting
Name: 13, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0             JobRole_Sales Representative     3.136652   23.026645
1            JobRole_Laboratory Technician     2.000593    7.393442
2                  JobRole_Human Resources     1.739854    5.696511
3                             OverTime_Yes     1.619529    5.050710
4                  JobRole_Sales Executive     1.506135    4.509268
5                  JobInvolvementLevel_Low     1.429772    4.177748
6         BusinessTravel_Travel_Frequently     1.425262    4.158949
7         EnvironmentSatisfactionLevel_Low     1.006729    2.736636
8               JobRole_Research Scientist     0.851472    2.343093
9             BusinessTravel_Travel_Rarely     0.754913    2.127427
10                   SatisfactionLevel_Low     0.464840    1.591759
11                SatisfactionLevel_Medium     0.289073    1.335189
12                        DistanceFromHome     0.277409    1.319707
13              JobInvolvementLevel_Medium     0.271597    1.312059
14          JobRole_Manufacturing Director     0.067428    1.069754
15                         JobRole_Manager    -0.177958    0.836978
16                   TrainingTimesLastYear    -0.178801    0.836273
17  EnvironmentSatisfactionLevel_Very High    -0.196445    0.821646
18     EnvironmentSatisfactionLevel_Medium    -0.204999    0.814648
19                               DailyRate    -0.224034    0.799288
20           JobInvolvementLevel_Very High    -0.373323    0.688443
21             SatisfactionLevel_Very High    -0.687318    0.502923
22               WorkLifeBalanceLevel_Best    -0.884559    0.412896
23               WorkLifeBalanceLevel_Good    -0.929913    0.394588
24               JobRole_Research Director    -1.473062    0.229222
25             WorkLifeBalanceLevel_Better    -1.530641    0.216397

array([[333,  37],
       [ 38,  33]])

Variable set: Modelo 5 — Estabilidade e Benefícios
Model: Logistic Regression Balanced
Best threshold: 0.74

Variable_Set                      Modelo 5 — Estabilidade e Benefícios
Model                                     Logistic Regression Balanced
Threshold                                                         0.74
Accuracy                                                         0.857
Precision                                                        0.587
Recall                                                            0.38
F1-score                                                         0.462
AUC                                                              0.795
Best_Score                                                       0.465
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.508
CV_F1_Mean                                                       0.459
F1_Gap                                                           0.049
Train_Recall_Mean                                                0.762
CV_Recall_Mean                                                   0.692
Recall_Gap                                                        0.07
Gap_Diagnosis                                    Stable generalization
Name: 14, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.686910    5.402759
1                  JobInvolvementLevel_Low     1.552584    4.723661
2                             OverTime_Yes     1.360964    3.899950
3             BusinessTravel_Travel_Rarely     0.947390    2.578969
4                      DistanceGroup_21-30     0.620389    1.859652
5         EnvironmentSatisfactionLevel_Low     0.610328    1.841035
6                    SatisfactionLevel_Low     0.543724    1.722409
7                      DistanceGroup_11-20     0.510265    1.665733
8                   StockOption_No Options     0.476613    1.610610
9                 SatisfactionLevel_Medium     0.302937    1.353830
10              JobInvolvementLevel_Medium     0.144139    1.155045
11                      DistanceGroup_6-10     0.138437    1.148478
12  EnvironmentSatisfactionLevel_Very High    -0.314179    0.730388
13     EnvironmentSatisfactionLevel_Medium    -0.328077    0.720308
14           JobInvolvementLevel_Very High    -0.329036    0.719617
15             SatisfactionLevel_Very High    -0.424979    0.653783
16               WorkLifeBalanceLevel_Best    -0.564695    0.568533
17               WorkLifeBalanceLevel_Good    -0.745717    0.474394
18                      StockOption_Medium    -0.753656    0.470643
19                         StockOption_Low    -0.804484    0.447319
20                  RoleStabilityGroup_2-3    -1.003693    0.366523
21                  RoleStabilityGroup_4-7    -1.212354    0.297496
22             WorkLifeBalanceLevel_Better    -1.343179    0.261014
23                   RoleStabilityGroup_8+    -1.944220    0.143099

array([[351,  19],
       [ 44,  27]])

Variable set: Modelo 1 — Função Profissional Misto
Model: Logistic Regression Balanced
Best threshold: 0.65

Variable_Set                      Modelo 1 — Função Profissional Misto
Model                                     Logistic Regression Balanced
Threshold                                                         0.65
Accuracy                                                         0.819
Precision                                                        0.442
Recall                                                           0.479
F1-score                                                         0.459
AUC                                                               0.78
Best_Score                                                       0.455
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.495
CV_F1_Mean                                                       0.454
F1_Gap                                                           0.041
Train_Recall_Mean                                                0.758
CV_Recall_Mean                                                   0.697
Recall_Gap                                                       0.061
Gap_Diagnosis                                    Stable generalization
Name: 15, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0             JobRole_Sales Representative     2.653173   14.199026
1            JobRole_Laboratory Technician     1.656400    5.240411
2                             OverTime_Yes     1.538984    4.659855
3                  JobRole_Human Resources     1.327438    3.771369
4                  JobInvolvementLevel_Low     1.227452    3.412525
5                  JobRole_Sales Executive     1.209355    3.351323
6         BusinessTravel_Travel_Frequently     1.192330    3.294750
7         EnvironmentSatisfactionLevel_Low     0.786336    2.195337
8             BusinessTravel_Travel_Rarely     0.649603    1.914781
9               JobRole_Research Scientist     0.482251    1.619716
10                   SatisfactionLevel_Low     0.363955    1.439010
11                        DistanceFromHome     0.239953    1.271189
12                SatisfactionLevel_Medium     0.228418    1.256611
13              JobInvolvementLevel_Medium     0.143015    1.153747
14          JobRole_Manufacturing Director    -0.043367    0.957560
15                   TrainingTimesLastYear    -0.161460    0.850901
16  EnvironmentSatisfactionLevel_Very High    -0.189492    0.827379
17           JobInvolvementLevel_Very High    -0.204060    0.815414
18                               DailyRate    -0.210650    0.810057
19     EnvironmentSatisfactionLevel_Medium    -0.268829    0.764274
20                         JobRole_Manager    -0.438123    0.645247
21               WorkLifeBalanceLevel_Best    -0.537170    0.584400
22             SatisfactionLevel_Very High    -0.636647    0.529063
23               WorkLifeBalanceLevel_Good    -0.649486    0.522314
24             WorkLifeBalanceLevel_Better    -1.253134    0.285608
25               JobRole_Research Director    -1.293301    0.274364

array([[327,  43],
       [ 37,  34]])

Variable set: Modelo 4 — Trajetória Organizacional
Model: Logistic Regression
Best threshold: 0.26

Variable_Set                      Modelo 4 — Trajetória Organizacional
Model                                              Logistic Regression
Threshold                                                         0.26
Accuracy                                                          0.81
Precision                                                        0.422
Recall                                                           0.493
F1-score                                                         0.455
AUC                                                               0.78
Best_Score                                                       0.401
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.424
CV_F1_Mean                                                       0.387
F1_Gap                                                           0.037
Train_Recall_Mean                                                0.298
CV_Recall_Mean                                                   0.271
Recall_Gap                                                       0.027
Gap_Diagnosis                                    Stable generalization
Name: 16, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  CareerStage_Entry-level     2.399364   11.016171
1                             OverTime_Yes     1.570337    4.808267
2                  JobInvolvementLevel_Low     1.557801    4.748368
3         BusinessTravel_Travel_Frequently     1.489852    4.436439
4         EnvironmentSatisfactionLevel_Low     1.014721    2.758593
5             BusinessTravel_Travel_Rarely     0.711106    2.036241
6                      DistanceGroup_21-30     0.561137    1.752665
7                    SatisfactionLevel_Low     0.512839    1.670026
8                      DistanceGroup_11-20     0.443903    1.558779
9               JobInvolvementLevel_Medium     0.193609    1.213621
10                SatisfactionLevel_Medium     0.192151    1.211853
11                  CareerStage_Mid career     0.080961    1.084329
12                      DistanceGroup_6-10     0.000000    1.000000
13     EnvironmentSatisfactionLevel_Medium    -0.012491    0.987586
14  EnvironmentSatisfactionLevel_Very High    -0.213209    0.807987
15                 CareerStage_Experienced    -0.239165    0.787285
16           JobInvolvementLevel_Very High    -0.427437    0.652179
17             SatisfactionLevel_Very High    -0.622554    0.536572
18               WorkLifeBalanceLevel_Best    -0.792820    0.452567
19               WorkLifeBalanceLevel_Good    -0.873304    0.417570
20                 CareerStage_Late career    -1.025092    0.358764
21             WorkLifeBalanceLevel_Better    -1.438079    0.237383

array([[322,  48],
       [ 36,  35]])

Variable set: Modelo 7 — Reduzido Conservador
Model: Logistic Regression Balanced
Best threshold: 0.51

Variable_Set                           Modelo 7 — Reduzido Conservador
Model                                     Logistic Regression Balanced
Threshold                                                         0.51
Accuracy                                                         0.728
Precision                                                        0.331
Recall                                                           0.676
F1-score                                                         0.444
AUC                                                              0.756
Best_Score                                                       0.414
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.435
CV_F1_Mean                                                       0.412
F1_Gap                                                           0.023
Train_Recall_Mean                                                0.717
CV_Recall_Mean                                                   0.672
Recall_Gap                                                       0.044
Gap_Diagnosis                                    Stable generalization
Name: 17, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                             OverTime_Yes     0.985013    2.677846
1                  JobInvolvementLevel_Low     0.599459    1.821134
2         EnvironmentSatisfactionLevel_Low     0.501550    1.651279
3         BusinessTravel_Travel_Frequently     0.366100    1.442100
4                    SatisfactionLevel_Low     0.101140    1.106431
5                      DistanceGroup_21-30     0.028143    1.028543
6            JobInvolvementLevel_Very High     0.000000    1.000000
7               JobInvolvementLevel_Medium     0.000000    1.000000
8      EnvironmentSatisfactionLevel_Medium     0.000000    1.000000
9             BusinessTravel_Travel_Rarely     0.000000    1.000000
10                SatisfactionLevel_Medium     0.000000    1.000000
11               WorkLifeBalanceLevel_Best     0.000000    1.000000
12               WorkLifeBalanceLevel_Good     0.000000    1.000000
13                     DistanceGroup_11-20     0.000000    1.000000
14                      DistanceGroup_6-10     0.000000    1.000000
15  EnvironmentSatisfactionLevel_Very High    -0.062590    0.939329
16             SatisfactionLevel_Very High    -0.508934    0.601136
17             WorkLifeBalanceLevel_Better    -0.551868    0.575873

array([[273,  97],
       [ 23,  48]])

Variable set: Modelo 7 — Reduzido Conservador Misto
Model: Logistic Regression Balanced
Best threshold: 0.5

Variable_Set                     Modelo 7 — Reduzido Conservador Misto
Model                                     Logistic Regression Balanced
Threshold                                                          0.5
Accuracy                                                         0.735
Precision                                                        0.333
Recall                                                           0.648
F1-score                                                          0.44
AUC                                                              0.781
Best_Score                                                       0.425
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.438
CV_F1_Mean                                                       0.425
F1_Gap                                                           0.013
Train_Recall_Mean                                                0.718
CV_Recall_Mean                                                   0.696
Recall_Gap                                                       0.021
Gap_Diagnosis                                    Stable generalization
Name: 18, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0         BusinessTravel_Travel_Frequently     1.371527    3.941363
1                  JobInvolvementLevel_Low     1.369535    3.933521
2                             OverTime_Yes     1.290736    3.635460
3             BusinessTravel_Travel_Rarely     0.780273    2.182067
4         EnvironmentSatisfactionLevel_Low     0.675447    1.964911
5                    SatisfactionLevel_Low     0.438070    1.549714
6                 SatisfactionLevel_Medium     0.240918    1.272416
7                         DistanceFromHome     0.194609    1.214836
8               JobInvolvementLevel_Medium     0.157601    1.170699
9                    TrainingTimesLastYear    -0.121125    0.885923
10                               DailyRate    -0.156863    0.854822
11           JobInvolvementLevel_Very High    -0.176111    0.838525
12     EnvironmentSatisfactionLevel_Medium    -0.223122    0.800017
13  EnvironmentSatisfactionLevel_Very High    -0.286152    0.751148
14               WorkLifeBalanceLevel_Best    -0.506378    0.602675
15             SatisfactionLevel_Very High    -0.542674    0.581192
16               WorkLifeBalanceLevel_Good    -0.577692    0.561192
17             WorkLifeBalanceLevel_Better    -1.164511    0.312075

array([[278,  92],
       [ 25,  46]])

Variable set: Modelo 4 — Trajetória Organizacional
Model: Logistic Regression Balanced
Best threshold: 0.57

Variable_Set                      Modelo 4 — Trajetória Organizacional
Model                                     Logistic Regression Balanced
Threshold                                                         0.57
Accuracy                                                         0.766
Precision                                                        0.349
Recall                                                           0.521
F1-score                                                         0.418
AUC                                                              0.771
Best_Score                                                       0.482
Best_Params          {'classifier__solver': 'liblinear', 'classifie...
Train_F1_Mean                                                    0.507
CV_F1_Mean                                                       0.477
F1_Gap                                                            0.03
Train_Recall_Mean                                                0.762
CV_Recall_Mean                                                   0.721
Recall_Gap                                                       0.041
Gap_Diagnosis                                    Stable generalization
Name: 19, dtype: object

                                   Feature  Coefficient  Odds_Ratio
0                  CareerStage_Entry-level     2.309079   10.065152
1                             OverTime_Yes     1.461711    4.313335
2                  JobInvolvementLevel_Low     1.389260    4.011880
3         BusinessTravel_Travel_Frequently     1.301969    3.676529
4         EnvironmentSatisfactionLevel_Low     0.900192    2.460074
5             BusinessTravel_Travel_Rarely     0.616466    1.852371
6                    SatisfactionLevel_Low     0.496854    1.643543
7                      DistanceGroup_21-30     0.487436    1.628137
8                      DistanceGroup_11-20     0.373423    1.452699
9               JobInvolvementLevel_Medium     0.181397    1.198891
10                SatisfactionLevel_Medium     0.115642    1.122594
11                  CareerStage_Mid career     0.110054    1.116339
12                      DistanceGroup_6-10    -0.017198    0.982949
13                 CareerStage_Experienced    -0.106912    0.898605
14     EnvironmentSatisfactionLevel_Medium    -0.167606    0.845687
15           JobInvolvementLevel_Very High    -0.231302    0.793500
16  EnvironmentSatisfactionLevel_Very High    -0.245949    0.781962
17             SatisfactionLevel_Very High    -0.496300    0.608779
18               WorkLifeBalanceLevel_Best    -0.516935    0.596346
19               WorkLifeBalanceLevel_Good    -0.716730    0.488347
20                 CareerStage_Late career    -0.872994    0.417699
21             WorkLifeBalanceLevel_Better    -1.335876    0.262928

array([[301,  69],
       [ 34,  37]])